export type EnumValueTypes<
  T extends Readonly<object>,
  K extends keyof T = keyof T
> = K extends keyof T ? T[K] : T[keyof T]

export const COMPANY_ENUM = {
  ID: 1,
} as const

export const AGE_OF_THE_ELDERLY = 40

export const ROLE_ENUM = {
  RECRUITER: 'RECRUITER',
  ADMIN: 'ADMIN',
  CANDIDATE: 'CANDIDATE',
  COMPANY: 'COMPANY',
} as const

export const GENDER_ENUM = {
  MASCULINE: 'MASCULINE',
  FEMININE: 'FEMININE',
  NEUTER: 'NEUTER',
  UNKNOWN: 'UNKNOWN',
  OTHER: 'OTHER',
} as const

export const SEXUAL_ORIENTATION_ENUM = {
  HETEROSEXUAL: 'HETEROSEXUAL',
  HOMOSEXUAL: 'HOMOSEXUAL',
  BISEXUAL: 'BISEXUAL',
  TRANSEXUAL: 'TRANSEXUAL',
  PANSEXUAL: 'PANSEXUAL',
  ASEXUAL: 'ASEXUAL',
  OTHER: 'OTHER',
  UNKNOWN: 'UNKNOWN',
} as const

export const RACE_ETHNICITY_ENUM = {
  YELLOW: 'YELLOW',
  WHITE: 'WHITE',
  INDIGENOUS: 'INDIGENOUS',
  HYSPANIC: 'HYSPANIC',
  BLACK: 'BLACK',
  DONT_KNOW: 'DONT_KNOW',
  UNKNOWN: 'UNKNOWN',
  OTHER: 'OTHER',
} as const

export const FAMILY_INCOME_ENUM = {
  A: 'FAMILY_INCOME_A',
  B1: 'FAMILY_INCOME_B1',
  B2: 'FAMILY_INCOME_B2',
  C: 'FAMILY_INCOME_C',
  D: 'FAMILY_INCOME_D',
  E: 'FAMILY_INCOME_E',
} as const

export const VULNERABILITY_ENUM = {
  ETHNIC_RACIAL: 'ETHNIC_RACIAL',
  INDIGENOUS_PEOPLE: 'INDIGENOUS_PEOPLE',
  LGBTQIA: 'LGBTQIA',
  DISABILITIES_PEOPLE: 'DISABILITIES_PEOPLE',
  AGE_GROUP: 'AGE_GROUP',
  FAMILY_INCOME_B: 'FAMILY_INCOME_B',
  FAMILY_INCOME_C: 'FAMILY_INCOME_C',
  FAMILY_INCOME_D: 'FAMILY_INCOME_D',
  FAMILY_INCOME_E: 'FAMILY_INCOME_E',
} as const

export const LOCATION_TYPE_ENUM = {
  ON_SITE: 'ON_SITE',
  REMOTE: 'REMOTE',
  HYBRID: 'HYBRID',
} as const

export const PHASE_STATUS_TYPE_ENUM = {
  SELECTED: 'SELECTED',
  HIRED: 'HIRED',
  APPLIED: 'APPLIED',
} as const

export const EMPLOYMENT_TYPE_ENUM = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  FREELANCE: 'FREELANCE',
  CONTRACT: 'CONTRACT',
  INTERNSHIP: 'INTERNSHIP',
  APPRENTICESHIP: 'APPRENTICESHIP',
  LEADERSHIP_PROGRAM: 'LEADERSHIP_PROGRAM',
  INDIRECT_CONTRACT: 'INDIRECT_CONTRACT',
} as const
